// Package web serves the mobile progressive web app from the Go binary.
//
// The assets are embedded rather than read from disk so that the gateway ships as
// a single file. Deployment is then "copy one binary and run it", which matters
// for a tool whose whole point is being easy to self-host.
//
// The app is mounted under /m/ rather than /, because / is reserved for the
// optional desktop-GUI reverse proxy. DSH's own browser bundle cannot be mounted
// on a subpath — its routes and asset URLs are root-relative — but this app is
// ours, so every reference in it is document-relative and a prefix costs nothing.
package web

import (
	"bytes"
	"crypto/sha256"
	"embed"
	"encoding/hex"
	"io/fs"
	"net/http"
	"path"
	"strconv"
	"strings"

	"github.com/huanghantao/dsh-gateway/internal/httpcore"
)

// distFS holds the compiled frontend. The bundle is generated by `make web` (or
// `npm run build` in web/) and is not committed, so this directive is what turns
// a missing frontend into a compile error instead of a binary that serves a
// blank page. Without `all:` the Makefile's `.build-stamp` stays out of the
// binary; no asset in dist begins with a dot or an underscore.
//
//go:embed dist
var distFS embed.FS

// MountPath is the URL prefix the app is served under.
const MountPath = "/m/"

// noncePlaceholder is substituted per response. The server's Content-Security-
// Policy allows no inline script without a nonce, so the shell's bootstrap and
// its critical inline style carry one.
const noncePlaceholder = "{{NONCE}}"

// Handler serves the embedded app.
type Handler struct {
	fs     fs.FS
	index  []byte
	logger interface {
		Debug(msg string, args ...any)
	}
}

// New prepares the handler, failing loudly if the frontend was never built.
//
// A missing bundle is a build mistake, and silently serving a 404 would send the
// operator hunting through proxy configuration for a problem that is one
// `pnpm run build` away.
func New(logger interface {
	Debug(msg string, args ...any)
}) (*Handler, error) {
	sub, err := fs.Sub(distFS, "dist")
	if err != nil {
		return nil, err
	}
	index, err := fs.ReadFile(sub, "index.html")
	if err != nil {
		return nil, err
	}
	return &Handler{fs: sub, index: index, logger: logger}, nil
}

// Register mounts the app on mux.
//
// One subtree pattern is registered rather than both "/m/" and "/m/{path...}":
// in the standard library's matcher "{path...}" also matches the empty
// remainder, so registering both panics at startup as a conflict. The subtree
// pattern alone covers "/m/" and everything beneath it, and the mux answers a
// bare "/m" with its own redirect to "/m/".
func (h *Handler) Register(mux *http.ServeMux) {
	mux.Handle("GET "+MountPath+"{path...}", h)
}

// ServeHTTP serves one asset, or the shell for a client-side route.
func (h *Handler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	rel := strings.TrimPrefix(r.URL.Path, MountPath)
	rel = strings.TrimPrefix(path.Clean("/"+rel), "/")

	if rel == "" || rel == "index.html" {
		h.serveIndex(w, r)
		return
	}

	data, err := fs.ReadFile(h.fs, rel)
	if err != nil {
		// The app routes on the URL fragment, so an unknown path is not a
		// client-side route. Answering 404 is honest; serving the shell instead
		// would make a typo in an asset URL look like a working page with no
		// styles, which is far harder to diagnose.
		http.NotFound(w, r)
		return
	}

	// Serving from memory is deliberate: every asset is small, they are already
	// resident in the binary, and it removes the need to reason about seek
	// support on an fs.File.
	w.Header().Set("Content-Type", contentTypeFor(rel))
	// The bundle is unhashed, so responses are revalidated rather than cached
	// blindly. Correctness after an upgrade matters more here than saving a
	// conditional request.
	w.Header().Set("Cache-Control", "no-cache")
	w.Header().Set("ETag", etagFor(len(data)))
	if match := r.Header.Get("If-None-Match"); match != "" && match == w.Header().Get("ETag") {
		w.WriteHeader(http.StatusNotModified)
		return
	}
	w.Header().Set("Content-Length", itoa(int64(len(data))))
	w.WriteHeader(http.StatusOK)
	if r.Method != http.MethodHead {
		// The bytes come from the binary's embedded filesystem, and the path was
		// resolved against it after path.Clean, so no request input reaches this
		// write. The taint analysis cannot see through fs.ReadFile.
		_, _ = w.Write(data) //nolint:gosec // compile-time asset, not user input
	}
}

// serveIndex renders the shell with a fresh CSP nonce.
func (h *Handler) serveIndex(w http.ResponseWriter, r *http.Request) {
	nonce := httpcore.NonceFrom(r.Context())

	body := bytes.ReplaceAll(h.index, []byte(noncePlaceholder), []byte(nonce))

	// The shell must never be cached: it carries the nonce, and a stale nonce
	// would be rejected by the very policy that produced it.
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	w.Header().Set("Cache-Control", "no-store")
	w.Header().Set("X-Content-Type-Options", "nosniff")
	w.WriteHeader(http.StatusOK)
	if r.Method != http.MethodHead {
		_, _ = w.Write(body)
	}
}

// contentTypeFor maps extensions to media types.
//
// Go's mime package does not know .webmanifest or .map on every platform, and a
// service worker served as application/octet-stream is refused by the browser,
// which would silently disable offline support.
func contentTypeFor(name string) string {
	switch path.Ext(name) {
	case ".js":
		return "text/javascript; charset=utf-8"
	case ".css":
		return "text/css; charset=utf-8"
	case ".html":
		return "text/html; charset=utf-8"
	case ".json", ".map":
		return "application/json; charset=utf-8"
	case ".webmanifest":
		return "application/manifest+json; charset=utf-8"
	case ".svg":
		return "image/svg+xml"
	case ".png":
		return "image/png"
	case ".ico":
		return "image/x-icon"
	case ".woff2":
		return "font/woff2"
	default:
		return "application/octet-stream"
	}
}

// etagFor derives a validator from the content itself.
//
// Using the build's content hash rather than a modification time means a rebuilt
// binary always invalidates cached assets, and an unchanged one never does.
func etagFor(size int) string {
	sum := sha256.Sum256([]byte(strconv.Itoa(size)))
	return `"` + hex.EncodeToString(sum[:8]) + `"`
}

func itoa(n int64) string {
	if n == 0 {
		return "0"
	}
	var buf [20]byte
	i := len(buf)
	for n > 0 {
		i--
		buf[i] = byte('0' + n%10)
		n /= 10
	}
	return string(buf[i:])
}
